In [1]:
import numpy as np

In [2]:
num_filters = 2
num_channels = 3
filter_height = 3
filter_width = 3

In [3]:
weights = np.random.randint(0,10,(num_filters, num_channels, filter_height, filter_width))

In [4]:
weights

array([[[[0, 4, 8],
         [4, 3, 0],
         [0, 6, 7]],

        [[9, 4, 0],
         [7, 1, 1],
         [0, 0, 1]],

        [[0, 6, 2],
         [1, 0, 5],
         [4, 8, 9]]],


       [[[3, 7, 7],
         [4, 3, 3],
         [0, 0, 4]],

        [[9, 5, 0],
         [7, 9, 6],
         [0, 9, 1]],

        [[8, 3, 0],
         [4, 2, 4],
         [9, 1, 7]]]])

In [5]:
weights_col = weights.reshape(num_filters, -1)

In [6]:
weights_col

array([[0, 4, 8, 4, 3, 0, 0, 6, 7, 9, 4, 0, 7, 1, 1, 0, 0, 1, 0, 6, 2, 1,
        0, 5, 4, 8, 9],
       [3, 7, 7, 4, 3, 3, 0, 0, 4, 9, 5, 0, 7, 9, 6, 0, 9, 1, 8, 3, 0, 4,
        2, 4, 9, 1, 7]])

In [7]:
weights_col2 = weights.reshape((num_filters, -1))

In [8]:
weights_col2

array([[0, 4, 8, 4, 3, 0, 0, 6, 7, 9, 4, 0, 7, 1, 1, 0, 0, 1, 0, 6, 2, 1,
        0, 5, 4, 8, 9],
       [3, 7, 7, 4, 3, 3, 0, 0, 4, 9, 5, 0, 7, 9, 6, 0, 9, 1, 8, 3, 0, 4,
        2, 4, 9, 1, 7]])

In [9]:
weights_col.shape

(2, 27)

In [10]:
weights_col2.shape

(2, 27)

In [11]:
bias = np.random.randint(0,10,num_filters)

In [12]:
bias

array([9, 3])

In [13]:
bias_col = bias.reshape(-1,1)

In [14]:
bias_col

array([[9],
       [3]])

In [15]:
X = np.random.randint(0, 10, (1, 3, 5, 5))
X

array([[[[3, 8, 9, 9, 7],
         [6, 7, 4, 9, 6],
         [0, 3, 7, 9, 8],
         [5, 1, 3, 0, 4],
         [9, 9, 2, 7, 9]],

        [[1, 5, 2, 5, 9],
         [2, 2, 8, 7, 8],
         [8, 1, 6, 2, 5],
         [8, 5, 1, 3, 7],
         [2, 0, 7, 4, 1]],

        [[7, 4, 6, 5, 6],
         [4, 5, 1, 6, 9],
         [0, 5, 0, 2, 0],
         [1, 3, 4, 9, 0],
         [0, 0, 7, 1, 4]]]])

In [16]:
filter_h = 3
filter_w = 3
stride = 2
padding = 1

In [17]:
from codes.utils import *

In [18]:
X_cols = im2col(X, filter_h, filter_w, stride, padding)

In [19]:
X_cols

array([[0, 0, 0, 0, 7, 9, 0, 1, 0],
       [0, 0, 0, 6, 4, 6, 5, 3, 4],
       [0, 0, 0, 7, 9, 0, 1, 0, 0],
       [0, 8, 9, 0, 3, 9, 0, 9, 7],
       [3, 9, 7, 0, 7, 8, 9, 2, 9],
       [8, 9, 0, 3, 9, 0, 9, 7, 0],
       [0, 7, 9, 0, 1, 0, 0, 0, 0],
       [6, 4, 6, 5, 3, 4, 0, 0, 0],
       [7, 9, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 7, 0, 5, 3],
       [0, 0, 0, 2, 8, 8, 8, 1, 7],
       [0, 0, 0, 2, 7, 0, 5, 3, 0],
       [0, 5, 5, 0, 1, 2, 0, 0, 4],
       [1, 2, 9, 8, 6, 5, 2, 7, 1],
       [5, 5, 0, 1, 2, 0, 0, 4, 0],
       [0, 2, 7, 0, 5, 3, 0, 0, 0],
       [2, 8, 8, 8, 1, 7, 0, 0, 0],
       [2, 7, 0, 5, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 6, 0, 3, 9],
       [0, 0, 0, 4, 1, 9, 1, 4, 0],
       [0, 0, 0, 5, 6, 0, 3, 9, 0],
       [0, 4, 5, 0, 5, 2, 0, 0, 1],
       [7, 6, 6, 0, 0, 0, 0, 7, 4],
       [4, 5, 0, 5, 2, 0, 0, 1, 0],
       [0, 5, 6, 0, 3, 9, 0, 0, 0],
       [4, 1, 9, 1, 4, 0, 0, 0, 0],
       [5, 6, 0, 3, 9, 0, 0, 0, 0]])

In [20]:
weights_col.shape

(2, 27)

In [21]:
X_cols.shape

(27, 9)

In [22]:
output_col = np.matmul(weights_col, X_cols) + bias_col

In [23]:
output_col

array([[208, 315, 247, 242, 374, 323, 110, 170, 165],
       [192, 423, 343, 326, 483, 521, 160, 281, 269]])

In [24]:
batch_size, num_channels, height, width = X.shape

In [25]:
num_filters, num_channels, filter_h, filter_w = weights.shape

In [26]:
output_height = int((height - filter_h + 2 * padding) / stride + 1)
output_width = int((width - filter_w + 2 * padding) / stride + 1)

In [27]:
output = np.zeros((batch_size, num_filters, output_height, output_width))

In [28]:
X_padded = np.pad(X, ((0, 0),
                        (0, 0),
                        (padding, padding),
                        (padding, padding)
                        ), 'constant')

In [29]:
biases = np.array([3,0])

In [30]:
for sample_index in range(batch_size):
            for filter_index in range(num_filters):
                for h in range(output_height):
                    for w in range(output_width):
                        output[sample_index, filter_index, h, w] = np.sum(
                            X_padded[sample_index,
                                         :,
                                         h * stride:h * stride + filter_height,
                                         w * stride:w * stride + filter_width
                                         ] * weights[filter_index]
                        ) + biases[filter_index]

In [31]:
output

array([[[[202., 309., 241.],
         [236., 368., 317.],
         [104., 164., 159.]],

        [[189., 420., 340.],
         [323., 480., 518.],
         [157., 278., 266.]]]])

In [32]:
output_2 = output_col.reshape(batch_size, num_filters, output_height, output_width)

In [33]:
output.shape

(1, 2, 3, 3)

In [34]:
output_2.shape

(1, 2, 3, 3)

In [35]:
output_2

array([[[[208, 315, 247],
         [242, 374, 323],
         [110, 170, 165]],

        [[192, 423, 343],
         [326, 483, 521],
         [160, 281, 269]]]])

In [36]:
output_col.shape

(2, 9)

In [40]:
output_col.shape

(2, 9)

In [42]:
np.array(np.hsplit(output_col, batch_size))

array([[[208, 315, 247, 242, 374, 323, 110, 170, 165],
        [192, 423, 343, 326, 483, 521, 160, 281, 269]]])

In [44]:
output_final = np.array(np.hsplit(output_col, batch_size)).reshape(batch_size, num_filters, output_height, output_width)

In [45]:
output_final.shape

(1, 2, 3, 3)