In [1]:
import numpy as np

In [2]:
num_filters = 2
num_channels = 3
filter_height = 3
filter_width = 3

In [3]:
weights = np.random.randint(0,10,(num_filters, num_channels, filter_height, filter_width))

In [4]:
weights

array([[[[3, 2, 8],
         [1, 1, 1],
         [5, 5, 2]],

        [[7, 8, 1],
         [1, 8, 1],
         [2, 7, 3]],

        [[6, 3, 1],
         [2, 7, 8],
         [9, 1, 6]]],


       [[[5, 5, 3],
         [8, 3, 5],
         [0, 6, 3]],

        [[3, 3, 6],
         [8, 0, 9],
         [5, 6, 6]],

        [[5, 3, 5],
         [4, 3, 2],
         [8, 5, 9]]]])

In [5]:
weights_col = weights.reshape(num_filters, -1)

In [6]:
weights_col

array([[3, 2, 8, 1, 1, 1, 5, 5, 2, 7, 8, 1, 1, 8, 1, 2, 7, 3, 6, 3, 1, 2,
        7, 8, 9, 1, 6],
       [5, 5, 3, 8, 3, 5, 0, 6, 3, 3, 3, 6, 8, 0, 9, 5, 6, 6, 5, 3, 5, 4,
        3, 2, 8, 5, 9]])

In [7]:
weights_col2 = weights.reshape((num_filters, -1))

In [8]:
weights_col2

array([[3, 2, 8, 1, 1, 1, 5, 5, 2, 7, 8, 1, 1, 8, 1, 2, 7, 3, 6, 3, 1, 2,
        7, 8, 9, 1, 6],
       [5, 5, 3, 8, 3, 5, 0, 6, 3, 3, 3, 6, 8, 0, 9, 5, 6, 6, 5, 3, 5, 4,
        3, 2, 8, 5, 9]])

In [9]:
weights_col.shape

(2, 27)

In [10]:
weights_col2.shape

(2, 27)

In [11]:
bias = np.random.randint(0,10,num_filters)

In [12]:
bias

array([9, 3])

In [13]:
bias_col = bias.reshape(-1,1)

In [14]:
bias_col

array([[9],
       [3]])

In [27]:
batch_size = 2

In [28]:
X = np.random.randint(0, 10, (batch_size, 3, 5, 5))
X

array([[[[3, 1, 2, 4, 8],
         [3, 3, 3, 5, 7],
         [9, 5, 7, 0, 4],
         [5, 9, 7, 4, 7],
         [7, 7, 1, 7, 0]],

        [[6, 2, 1, 2, 2],
         [1, 6, 2, 3, 9],
         [9, 3, 1, 0, 6],
         [1, 5, 8, 5, 1],
         [3, 7, 2, 4, 5]],

        [[3, 3, 1, 3, 5],
         [1, 8, 8, 4, 5],
         [9, 9, 7, 5, 3],
         [9, 8, 1, 1, 3],
         [1, 4, 4, 7, 7]]],


       [[[7, 1, 7, 4, 3],
         [9, 7, 6, 2, 7],
         [6, 5, 2, 6, 1],
         [8, 2, 3, 4, 3],
         [1, 8, 5, 8, 9]],

        [[1, 7, 2, 0, 7],
         [3, 3, 4, 9, 4],
         [3, 3, 9, 4, 1],
         [4, 0, 2, 8, 9],
         [8, 9, 8, 0, 2]],

        [[0, 5, 5, 8, 9],
         [1, 1, 7, 1, 2],
         [1, 8, 9, 4, 1],
         [5, 7, 5, 1, 3],
         [4, 5, 1, 1, 5]]]])

In [16]:
filter_h = 3
filter_w = 3
stride = 2
padding = 1

In [17]:
from codes.utils import *

In [29]:
X_padded = np.pad(X, ((0, 0),
                        (0, 0),
                        (padding, padding),
                        (padding, padding)
                        ), 'constant')
                        

In [76]:
X_padded

array([[[[0, 0, 0, 0, 0, 0, 0],
         [0, 3, 1, 2, 4, 8, 0],
         [0, 3, 3, 3, 5, 7, 0],
         [0, 9, 5, 7, 0, 4, 0],
         [0, 5, 9, 7, 4, 7, 0],
         [0, 7, 7, 1, 7, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0],
         [0, 6, 2, 1, 2, 2, 0],
         [0, 1, 6, 2, 3, 9, 0],
         [0, 9, 3, 1, 0, 6, 0],
         [0, 1, 5, 8, 5, 1, 0],
         [0, 3, 7, 2, 4, 5, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0],
         [0, 3, 3, 1, 3, 5, 0],
         [0, 1, 8, 8, 4, 5, 0],
         [0, 9, 9, 7, 5, 3, 0],
         [0, 9, 8, 1, 1, 3, 0],
         [0, 1, 4, 4, 7, 7, 0],
         [0, 0, 0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0, 0, 0],
         [0, 7, 1, 7, 4, 3, 0],
         [0, 9, 7, 6, 2, 7, 0],
         [0, 6, 5, 2, 6, 1, 0],
         [0, 8, 2, 3, 4, 3, 0],
         [0, 1, 8, 5, 8, 9, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0],
         [0, 1, 7, 2, 0, 7, 0],
         [0, 3, 3, 4, 9, 4, 0]

In [31]:
h, w, d = get_indices(X.shape, filter_h, filter_w, stride, padding)

In [32]:
X_cols = X_padded[:, d, h, w]

In [33]:
X_cols

array([[[0, 0, 0, 0, 3, 5, 0, 9, 4],
        [0, 0, 0, 3, 3, 7, 5, 7, 7],
        [0, 0, 0, 3, 5, 0, 9, 4, 0],
        [0, 1, 4, 0, 5, 0, 0, 7, 7],
        [3, 2, 8, 9, 7, 4, 7, 1, 0],
        [1, 4, 0, 5, 0, 0, 7, 7, 0],
        [0, 3, 5, 0, 9, 4, 0, 0, 0],
        [3, 3, 7, 5, 7, 7, 0, 0, 0],
        [3, 5, 0, 9, 4, 0, 0, 0, 0],
        [0, 0, 0, 0, 6, 3, 0, 5, 5],
        [0, 0, 0, 1, 2, 9, 1, 8, 1],
        [0, 0, 0, 6, 3, 0, 5, 5, 0],
        [0, 2, 2, 0, 3, 0, 0, 7, 4],
        [6, 1, 2, 9, 1, 6, 3, 2, 5],
        [2, 2, 0, 3, 0, 0, 7, 4, 0],
        [0, 6, 3, 0, 5, 5, 0, 0, 0],
        [1, 2, 9, 1, 8, 1, 0, 0, 0],
        [6, 3, 0, 5, 5, 0, 0, 0, 0],
        [0, 0, 0, 0, 8, 4, 0, 8, 1],
        [0, 0, 0, 1, 8, 5, 9, 1, 3],
        [0, 0, 0, 8, 4, 0, 8, 1, 0],
        [0, 3, 3, 0, 9, 5, 0, 4, 7],
        [3, 1, 5, 9, 7, 3, 1, 4, 7],
        [3, 3, 0, 9, 5, 0, 4, 7, 0],
        [0, 8, 4, 0, 8, 1, 0, 0, 0],
        [1, 8, 5, 9, 1, 3, 0, 0, 0],
        [8, 4, 0, 8, 1, 0, 0, 0, 0]],


In [34]:
X_cols.shape

(2, 27, 9)

In [41]:
X_cols.transpose(1, 2, 0).reshape(filter_h * filter_w * X.shape[1], -1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 3, 7, 5, 2, 0, 0, 9, 2, 4, 4],
       [0, 0, 0, 0, 0, 0, 3, 9, 3, 6, 7, 7, 5, 8, 7, 3, 7, 3],
       [0, 0, 0, 0, 0, 0, 3, 7, 5, 2, 0, 0, 9, 2, 4, 4, 0, 0],
       [0, 0, 1, 1, 4, 4, 0, 0, 5, 5, 0, 6, 0, 0, 7, 8, 7, 8],
       [3, 7, 2, 7, 8, 3, 9, 6, 7, 2, 4, 1, 7, 1, 1, 5, 0, 9],
       [1, 1, 4, 4, 0, 0, 5, 5, 0, 6, 0, 0, 7, 8, 7, 8, 0, 0],
       [0, 0, 3, 7, 5, 2, 0, 0, 9, 2, 4, 4, 0, 0, 0, 0, 0, 0],
       [3, 9, 3, 6, 7, 7, 5, 8, 7, 3, 7, 3, 0, 0, 0, 0, 0, 0],
       [3, 7, 5, 2, 0, 0, 9, 2, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 6, 3, 3, 9, 0, 0, 5, 0, 5, 8],
       [0, 0, 0, 0, 0, 0, 1, 3, 2, 4, 9, 4, 1, 4, 8, 2, 1, 9],
       [0, 0, 0, 0, 0, 0, 6, 3, 3, 9, 0, 0, 5, 0, 5, 8, 0, 0],
       [0, 0, 2, 7, 2, 0, 0, 0, 3, 3, 0, 4, 0, 0, 7, 9, 4, 0],
       [6, 1, 1, 2, 2, 7, 9, 3, 1, 9, 6, 1, 3, 8, 2, 8, 5, 2],
       [2, 7, 2, 0, 0, 0, 3, 3, 0, 4, 0, 0, 7, 9, 4, 0, 0, 0],
       [0, 0, 6, 3, 3, 9, 0, 0, 5, 0, 5, 8, 0, 0, 0, 0,

In [40]:
filter_h * filter_w * X.shape[1]

27

In [35]:
np.concatenate(X_cols, axis=-1).shape

(27, 18)

In [79]:
X_cols = im2col(X, filter_h, filter_w, stride, padding)

In [19]:
X_cols

array([[0, 0, 0, 0, 7, 9, 0, 1, 0],
       [0, 0, 0, 6, 4, 6, 5, 3, 4],
       [0, 0, 0, 7, 9, 0, 1, 0, 0],
       [0, 8, 9, 0, 3, 9, 0, 9, 7],
       [3, 9, 7, 0, 7, 8, 9, 2, 9],
       [8, 9, 0, 3, 9, 0, 9, 7, 0],
       [0, 7, 9, 0, 1, 0, 0, 0, 0],
       [6, 4, 6, 5, 3, 4, 0, 0, 0],
       [7, 9, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 7, 0, 5, 3],
       [0, 0, 0, 2, 8, 8, 8, 1, 7],
       [0, 0, 0, 2, 7, 0, 5, 3, 0],
       [0, 5, 5, 0, 1, 2, 0, 0, 4],
       [1, 2, 9, 8, 6, 5, 2, 7, 1],
       [5, 5, 0, 1, 2, 0, 0, 4, 0],
       [0, 2, 7, 0, 5, 3, 0, 0, 0],
       [2, 8, 8, 8, 1, 7, 0, 0, 0],
       [2, 7, 0, 5, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 6, 0, 3, 9],
       [0, 0, 0, 4, 1, 9, 1, 4, 0],
       [0, 0, 0, 5, 6, 0, 3, 9, 0],
       [0, 4, 5, 0, 5, 2, 0, 0, 1],
       [7, 6, 6, 0, 0, 0, 0, 7, 4],
       [4, 5, 0, 5, 2, 0, 0, 1, 0],
       [0, 5, 6, 0, 3, 9, 0, 0, 0],
       [4, 1, 9, 1, 4, 0, 0, 0, 0],
       [5, 6, 0, 3, 9, 0, 0, 0, 0]])

In [84]:
weights_col.shape

(2, 27)

In [85]:
X_cols.shape

(27, 18)

In [86]:
output_col = np.matmul(weights_col, X_cols) + bias_col

In [87]:
output_col

array([[203, 244, 250, 410, 579, 337, 223, 372, 207, 168, 305, 253, 342,
        496, 296, 245, 254, 240],
       [196, 325, 270, 443, 561, 271, 285, 440, 227, 227, 346, 232, 359,
        563, 335, 257, 365, 213]])

In [88]:
batch_size, num_channels, height, width = X.shape

In [89]:
num_filters, num_channels, filter_h, filter_w = weights.shape

In [90]:
output_height = int((height - filter_h + 2 * padding) / stride + 1)
output_width = int((width - filter_w + 2 * padding) / stride + 1)

In [91]:
output = np.zeros((batch_size, num_filters, output_height, output_width))

In [92]:
X_padded = np.pad(X, ((0, 0),
                        (0, 0),
                        (padding, padding),
                        (padding, padding)
                        ), 'constant')

In [93]:
biases = np.array([9,3])

In [94]:
for sample_index in range(batch_size):
            for filter_index in range(num_filters):
                for h in range(output_height):
                    for w in range(output_width):
                        output[sample_index, filter_index, h, w] = np.sum(
                            X_padded[sample_index,
                                         :,
                                         h * stride:h * stride + filter_height,
                                         w * stride:w * stride + filter_width
                                         ] * weights[filter_index]
                        ) + biases[filter_index]

In [95]:
output

array([[[[203., 244., 250.],
         [410., 579., 337.],
         [223., 372., 207.]],

        [[196., 325., 270.],
         [443., 561., 271.],
         [285., 440., 227.]]],


       [[[168., 305., 253.],
         [342., 496., 296.],
         [245., 254., 240.]],

        [[227., 346., 232.],
         [359., 563., 335.],
         [257., 365., 213.]]]])

In [96]:
output_2 = output_col.reshape(batch_size, num_filters, output_height, output_width)

In [33]:
output.shape

(1, 2, 3, 3)

In [34]:
output_2.shape

(1, 2, 3, 3)

In [97]:
output_2

array([[[[203, 244, 250],
         [410, 579, 337],
         [223, 372, 207]],

        [[168, 305, 253],
         [342, 496, 296],
         [245, 254, 240]]],


       [[[196, 325, 270],
         [443, 561, 271],
         [285, 440, 227]],

        [[227, 346, 232],
         [359, 563, 335],
         [257, 365, 213]]]])

In [36]:
output_col.shape

(2, 9)

In [40]:
output_col.shape

(2, 9)

In [42]:
np.array(np.hsplit(output_col, batch_size))

array([[[208, 315, 247, 242, 374, 323, 110, 170, 165],
        [192, 423, 343, 326, 483, 521, 160, 281, 269]]])

In [44]:
output_final = np.array(np.hsplit(output_col, batch_size)).reshape(batch_size, num_filters, output_height, output_width)

In [45]:
output_final.shape

(1, 2, 3, 3)

In [42]:
from numpy.lib.stride_tricks import as_strided

In [43]:

arr = np.arange(1, 25).reshape(4, 6) % 10


In [44]:
arr

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 0, 1, 2],
       [3, 4, 5, 6, 7, 8],
       [9, 0, 1, 2, 3, 4]], dtype=int32)

In [48]:
arr.shape

(4, 6)

In [45]:
sub_shape = (3, 3)

In [46]:

view_shape = tuple(np.subtract(arr.shape, sub_shape) + 1) + sub_shape

In [47]:
view_shape

(2, 4, 3, 3)

In [56]:
as_strided(arr, view_shape, arr.strides * 2).shape

(2, 4, 3, 3)

In [51]:
arr_view = as_strided(arr, view_shape, arr.strides * 2)

In [52]:
arr_view

array([[[[1, 2, 3],
         [7, 8, 9],
         [3, 4, 5]],

        [[2, 3, 4],
         [8, 9, 0],
         [4, 5, 6]],

        [[3, 4, 5],
         [9, 0, 1],
         [5, 6, 7]],

        [[4, 5, 6],
         [0, 1, 2],
         [6, 7, 8]]],


       [[[7, 8, 9],
         [3, 4, 5],
         [9, 0, 1]],

        [[8, 9, 0],
         [4, 5, 6],
         [0, 1, 2]],

        [[9, 0, 1],
         [5, 6, 7],
         [1, 2, 3]],

        [[0, 1, 2],
         [6, 7, 8],
         [2, 3, 4]]]], dtype=int32)

In [53]:

arr_view = arr_view.reshape((-1,) + sub_shape)

In [54]:
arr_view

array([[[1, 2, 3],
        [7, 8, 9],
        [3, 4, 5]],

       [[2, 3, 4],
        [8, 9, 0],
        [4, 5, 6]],

       [[3, 4, 5],
        [9, 0, 1],
        [5, 6, 7]],

       [[4, 5, 6],
        [0, 1, 2],
        [6, 7, 8]],

       [[7, 8, 9],
        [3, 4, 5],
        [9, 0, 1]],

       [[8, 9, 0],
        [4, 5, 6],
        [0, 1, 2]],

       [[9, 0, 1],
        [5, 6, 7],
        [1, 2, 3]],

       [[0, 1, 2],
        [6, 7, 8],
        [2, 3, 4]]], dtype=int32)

In [55]:
arr_view.shape

(8, 3, 3)

In [58]:
arr = np.arange(1, 26).reshape(5, 5)

In [59]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [73]:
stride_count = 3

In [74]:
new_stride = (arr.strides[0] * stride_count,arr.strides[1] * stride_count,arr.strides[0],arr.strides[1])

In [68]:
new_stride

(40, 8, 20, 4)

In [75]:
as_strided(arr, shape=(2,2,3,3), strides=new_stride)

array([[[[          1,           2,           3],
         [          6,           7,           8],
         [         11,          12,          13]],

        [[          4,           5,           6],
         [          9,          10,          11],
         [         14,          15,          16]]],


       [[[         16,          17,          18],
         [         21,          22,          23],
         [  859202354,  1116456951, -1879046912]],

        [[         19,          20,          21],
         [         24,          25,   859202354],
         [ -563353952,       32764, -2023983936]]]])